server:
  port: 8101
spring:
  config:
    import:
    - classpath:config/dev/mysql/application.yml
    - classpath:config/dev/redis/application.yml
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
